'use client';

import { FluentProvider, teamsDarkTheme } from '@fluentui/react-components';
import { Inter } from 'next/font/google';
import './globals.css';
import Footer from './layout/footer/page.tsx';
import Header from './layout/header/page.tsx';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FluentProvider theme={teamsDarkTheme}>
          <Header />
          {children}
          <Footer />
        </FluentProvider>
      </body>
    </html>
  );
}
